---
name: Rajarathna Opthalmology

on:
  workflow_dispatch:

jobs:
  Zip:
    runs-on: ubuntu-latest
    steps:

      - name: Create Zip
        run: |
          gh release download "optha" -D "optha" -R AdityaGarg8/MBBS
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: "Rajarathna Opthalmology"
          path: ${{ github.workspace }}/"optha"
